 platform :ios, '9.0'
source 'https://github.com/linkplayapp/LPSpecsiOS.git'
# Your CocosPods repo source address
source 'https://cdn.cocoapods.org/'

target 'LPMusicKitDemo' do

  pod "LPMusicKitiOS", :git => "https://github.com/linkplayapp/LPMusicKitiOS.git"
  pod "LPBLESetupiOS", :git => "https://github.com/linkplayapp/LPBLESetupiOS.git"
  pod "LPMSNASiOS", :git => "https://github.com/linkplayapp/LPMSNASiOS.git"
  pod "LPMSMediaLibraryiOS", :git => "https://github.com/linkplayapp/LPMSMediaLibraryiOS.git"
  pod "LPAlexaKitiOS", :git => "https://github.com/linkplayapp/LPAlexaKitiOS.git"

  
  # Third-party libraries used by Demo
  pod "MBProgressHUD"
  pod "SDWebImage"
  pod 'Toast', '~> 4.0.0'


end
