 platform :ios, '9.0'
source 'https://github.com/linkplayapp/LPSpecsiOS.git'
# Your CocosPods repo source address
source 'https://github.com/CocoaPods/Specs.git'

target 'LPMusicKitDemo' do

  pod "LPMusicKitiOS", :git => "https://github.com/linkplayapp/LPMusicKitiOS.git"
  pod "LPBLESetupiOS", :git => "https://github.com/linkplayapp/LPBLESetupiOS.git"
  pod "LPMSNASiOS", :git => "https://github.com/linkplayapp/LPMSNASiOS.git"
  pod "LPMSMediaLibraryiOS", :git => "https://github.com/linkplayapp/LPMSMediaLibraryiOS.git"
  pod "LPMSTuneIniOS", :git => "https://github.com/linkplayapp/LPMSTuneIniOS.git"
  pod "LPAlexaKitiOS", :git => "https://github.com/linkplayapp/LPAlexaKitiOS.git"
  pod "LPMSAmazonMusiciOS", :git => "https://github.com/linkplayapp/LPMSAmazonMusiciOS.git"
  
  
  # Third-party libraries used by Demo
  pod "SDWebImage"
  pod 'Toast', '~> 4.0.0'


end
